In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

In [3]:
transactions = pd.read_csv(r"D:\AnalytixLabs\Case Studies\Python Case Study\Case Study 1 - Retail Case Study\Transactions.csv")
customer = pd.read_csv(r"D:\AnalytixLabs\Case Studies\Python Case Study\Case Study 1 - Retail Case Study\Customer.csv")
prod_cat_info = pd.read_csv(r"D:\AnalytixLabs\Case Studies\Python Case Study\Case Study 1 - Retail Case Study\prod_cat_info.csv")

In [4]:
temp = pd.merge(left= transactions, right= customer, left_on= 'cust_id', right_on= 'customer_Id', how= 'inner')

In [5]:
Customer_final = pd.merge(left= temp, right = prod_cat_info, left_on=['prod_cat_code', 'prod_subcat_code'], \
         right_on=['prod_cat_code', 'prod_sub_cat_code'], how= 'inner')

In [6]:
Customer_final.dtypes

transaction_id         int64
cust_id                int64
tran_date             object
prod_subcat_code       int64
prod_cat_code          int64
Qty                    int64
Rate                   int64
Tax                  float64
total_amt            float64
Store_type            object
customer_Id            int64
DOB                   object
Gender                object
city_code            float64
prod_cat              object
prod_sub_cat_code      int64
prod_subcat           object
dtype: object

In [7]:
Customer_final.head(10)

,transaction_id,cust_id,tran_date,prod_subcat_code,prod_cat_code,Qty,Rate,Tax,total_amt,Store_type,customer_Id,DOB,Gender,city_code,prod_cat,prod_sub_cat_code,prod_subcat
0,80712190438,270351,28-02-2014,1,1,-5,-772,405.300,-4265.300,e-Shop,270351,26-09-1981,M,5.0,Clothing,1,Women
1,29258453508,270384,27-02-2014,5,3,-5,-1497,785.925,-8270.925,e-Shop,270384,11-05-1973,F,8.0,Electronics,5,Computers
2,51750724947,273420,24-02-2014,6,5,-2,-791,166.110,-1748.110,TeleShop,273420,27-07-1992,M,8.0,Books,6,DIY
3,93274880719,271509,24-02-2014,11,6,-3,-1363,429.345,-4518.345,e-Shop,271509,08-06-1981,M,3.0,Home and kitchen,11,Bath
4,51750724947,273420,23-02-2014,6,5,-2,-791,166.110,-1748.110,TeleShop,273420,27-07-1992,M,8.0,Books,6,DIY
5,97439039119,272357,23-02-2014,8,3,-2,-824,173.040,-1821.040,TeleShop,272357,09-10-1982,F,6.0,Electronics,8,Personal Appliances
6,45649838090,273667,22-02-2014,11,6,-1,-1450,152.250,-1602.250,e-Shop,273667,29-05-1981,M,9.0,Home and kitchen,11,Bath
7,22643667930,271489,22-02-2014,12,6,-1,-1225,128.625,-1353.625,TeleShop,271489,21-04-1971,M,9.0,Home and kitchen,12,Tools
8,79792372943,275108,22-02-2014,3,1,-3,-908,286.020,-3010.020,MBR,275108,04-11-1971,F,8.0,Clothing,3,Kids
9,50076728598,269014,21-02-2014,8,3,-4,-581,244.020,-2568.020,e-Shop,269014,27-11-1979,F,3.0,Electronics,8,Personal Appliances

In [8]:
Customer_final.describe().loc['min':'max']

,transaction_id,cust_id,prod_subcat_code,prod_cat_code,Qty,Rate,Tax,total_amt,customer_Id,city_code,prod_sub_cat_code
min,3.268991e+06,266783.0,1.0,1.0,-5.0,-1499.0,7.350,-8270.925,266783.0,1.0,1.0
25%,2.493864e+10,268935.0,3.0,2.0,1.0,312.0,98.280,762.450,268935.0,3.0,3.0
50%,5.009313e+10,270980.0,5.0,4.0,3.0,710.0,199.080,1754.740,270980.0,5.0,5.0
75%,7.533000e+10,273114.0,10.0,5.0,4.0,1109.0,365.715,3569.150,273114.0,8.0,10.0
max,9.998755e+10,275265.0,12.0,6.0,5.0,1500.0,787.500,8287.500,275265.0,10.0,12.0

In [9]:
Customer_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23053 entries, 0 to 23052
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   transaction_id     23053 non-null  int64
 1   cust_id            23053 non-null  int64
 2   tran_date          23053 non-null  object
 3   prod_subcat_code   23053 non-null  int64
 4   prod_cat_code      23053 non-null  int64
 5   Qty                23053 non-null  int64
 6   Rate               23053 non-null  int64
 7   Tax                23053 non-null  float64
 8   total_amt          23053 non-null  float64
 9   Store_type         23053 non-null  object
 10  customer_Id        23053 non-null  int64
 11  DOB                23053 non-null  object
 12  Gender             23044 non-null  object
 13  city_code          23045 non-null  float64
 14  prod_cat           23053 non-null  object
 15  prod_sub_cat_code  23053 non-null  int64
 16  prod_subcat        23053 non-null  object
dtypes: float64(3), int64(8), object(6)
memory usage: 3.0+ MB

In [10]:
df = Customer_final.select_dtypes(include= 'object')

In [11]:
df

        tran_date Store_type         DOB Gender          prod_cat prod_subcat
0      28-02-2014     e-Shop  26-09-1981      M          Clothing       Women
1      27-02-2014     e-Shop  11-05-1973      F       Electronics   Computers
2      24-02-2014   TeleShop  27-07-1992      M             Books         DIY
3      24-02-2014     e-Shop  08-06-1981      M  Home and kitchen        Bath
4      23-02-2014   TeleShop  27-07-1992      M             Books         DIY
...           ...        ...         ...    ...               ...         ...
23048  25-01-2011     e-Shop  21-02-1972      M             Books    Academic
23049  25-01-2011     e-Shop  27-04-1984      M          Clothing        Mens
23050  25-01-2011        MBR  20-06-1976      M  Home and kitchen  Furnishing
23051  25-01-2011   TeleShop  22-05-1970      M             Books    Children
23052  25-01-2011   TeleShop  15-01-1982      M             Books    Children

[23053 rows x 6 columns]

In [12]:
df = df.drop(columns= ['tran_date', 'DOB'])

In [13]:
df

      Store_type Gender          prod_cat prod_subcat
0         e-Shop      M          Clothing       Women
1         e-Shop      F       Electronics   Computers
2       TeleShop      M             Books         DIY
3         e-Shop      M  Home and kitchen        Bath
4       TeleShop      M             Books         DIY
...          ...    ...               ...         ...
23048     e-Shop      M             Books    Academic
23049     e-Shop      M          Clothing        Mens
23050        MBR      M  Home and kitchen  Furnishing
23051   TeleShop      M             Books    Children
23052   TeleShop      M             Books    Children

[23053 rows x 4 columns]

In [14]:
print(df.Store_type.value_counts(), end= '\n\n\n')
print(df.Gender.value_counts(), end= '\n\n\n')
print(df[['prod_cat','prod_subcat']].value_counts(), end= '\n\n\n')

Store_type
e-Shop            9311
MBR               4661
Flagship store    4577
TeleShop          4504
Name: count, dtype: int64


Gender
M    11811
F    11233
Name: count, dtype: int64


prod_cat          prod_subcat
Home and kitchen  Tools                  1062
Footwear          Women                  1048
Books             Fiction                1043
Home and kitchen  Kitchen                1037
Books             Children               1035
Electronics       Mobiles                1031
Books             Comics                 1031
Home and kitchen  Bath                   1023
Footwear          Kids                   1009
Home and kitchen  Furnishing             1007
Clothing          Women                  1005
Books             Non-Fiction            1004
Bags              Mens                   1003
                  Women                   995
Books             DIY                     989
Clothing          Kids                    988
Electronics       Cameras                 985
                  Personal Appliances     972
Clothing          Mens                    967
Books             Academic                967
Electronics       Computers               958
                  Audio and video         952
Footwear          Mens                    942
Name: count, dtype: int64

In [15]:
Customer_final.head()

,transaction_id,cust_id,tran_date,prod_subcat_code,prod_cat_code,Qty,Rate,Tax,total_amt,Store_type,customer_Id,DOB,Gender,city_code,prod_cat,prod_sub_cat_code,prod_subcat
0,80712190438,270351,28-02-2014,1,1,-5,-772,405.300,-4265.300,e-Shop,270351,26-09-1981,M,5.0,Clothing,1,Women
1,29258453508,270384,27-02-2014,5,3,-5,-1497,785.925,-8270.925,e-Shop,270384,11-05-1973,F,8.0,Electronics,5,Computers
2,51750724947,273420,24-02-2014,6,5,-2,-791,166.110,-1748.110,TeleShop,273420,27-07-1992,M,8.0,Books,6,DIY
3,93274880719,271509,24-02-2014,11,6,-3,-1363,429.345,-4518.345,e-Shop,271509,08-06-1981,M,3.0,Home and kitchen,11,Bath
4,51750724947,273420,23-02-2014,6,5,-2,-791,166.110,-1748.110,TeleShop,273420,27-07-1992,M,8.0,Books,6,DIY

In [16]:
Customer_final.tran_date = pd.to_datetime(
    Customer_final['tran_date'],
    format='mixed',
    dayfirst=True
)

In [17]:
td = max(Customer_final.tran_date) - min(Customer_final.tran_date)
print('Time Range in days:', td.days)

Time Range in days: 1130

In [18]:
count = len(transactions[transactions.total_amt < 0])

print('Count of transactions where the total amount of transaction were negative:',count)

Count of transactions where the total amount of transaction were negative: 2177

In [22]:
Customer_final.head()

,transaction_id,cust_id,tran_date,prod_subcat_code,prod_cat_code,Qty,Rate,Tax,total_amt,Store_type,customer_Id,DOB,Gender,city_code,prod_cat,prod_sub_cat_code,prod_subcat
0,80712190438,270351,2014-02-28,1,1,-5,-772,405.300,-4265.300,e-Shop,270351,26-09-1981,M,5.0,Clothing,1,Women
1,29258453508,270384,2014-02-27,5,3,-5,-1497,785.925,-8270.925,e-Shop,270384,11-05-1973,F,8.0,Electronics,5,Computers
2,51750724947,273420,2014-02-24,6,5,-2,-791,166.110,-1748.110,TeleShop,273420,27-07-1992,M,8.0,Books,6,DIY
3,93274880719,271509,2014-02-24,11,6,-3,-1363,429.345,-4518.345,e-Shop,271509,08-06-1981,M,3.0,Home and kitchen,11,Bath
4,51750724947,273420,2014-02-23,6,5,-2,-791,166.110,-1748.110,TeleShop,273420,27-07-1992,M,8.0,Books,6,DIY

In [26]:
df = Customer_final.drop_duplicates(subset= ['transaction_id'])

In [28]:
pd.pivot_table(data= df
               , index= 'prod_cat', 
               columns= 'Gender', 
               values = 'transaction_id', 
               aggfunc= 'count')

Gender               F     M
prod_cat
Bags               890   899
Books             2657  2825
Clothing          1286  1388
Electronics       2135  2351
Footwear          1380  1327
Home and kitchen  1810  1922